// This is data generated by the QPX Demo
// We use will use this data to test development without having to directly query to QPX API
// This is a response object of the five flights:

/*

5 solutions found.

Solution#   1   Sale Price: USD76.10
         Slice 0
             VX 898 SFO 2015-06-01T08:35-07:00 LAX 2015-06-01T09:55-07:00

Solution#   2   Sale Price: USD76.10
         Slice 0
             VX 932 SFO 2015-06-01T16:30-07:00 LAX 2015-06-01T17:50-07:00

Solution#   3   Sale Price: USD76.10
         Slice 0
             VX 928 SFO 2015-06-01T13:25-07:00 LAX 2015-06-01T14:45-07:00

Solution#   4   Sale Price: USD76.10
         Slice 0
             VX 922 SFO 2015-06-01T06:50-07:00 LAX 2015-06-01T08:05-07:00

Solution#   5   Sale Price: USD76.10
         Slice 0
             VX 924 SFO 2015-06-01T11:35-07:00 LAX 2015-06-01T12:55-07:00

*/

{
 "kind": "qpxExpress#tripsSearch",
 "trips": {
  "kind": "qpxexpress#tripOptions",
  "requestId": "EXiZ7ni53gyx7n0Eq0Ljp3",
  "data": {
   "kind": "qpxexpress#data",
   "airport": [
    {
     "kind": "qpxexpress#airportData",
     "code": "LAX",
     "city": "LAX",
     "name": "Los Angeles International"
    },
    {
     "kind": "qpxexpress#airportData",
     "code": "SFO",
     "city": "SFO",
     "name": "San Francisco International"
    }
   ],
   "city": [
    {
     "kind": "qpxexpress#cityData",
     "code": "LAX",
     "name": "Los Angeles"
    },
    {
     "kind": "qpxexpress#cityData",
     "code": "SFO",
     "name": "San Francisco"
    }
   ],
   "aircraft": [
    {
     "kind": "qpxexpress#aircraftData",
     "code": "319",
     "name": "Airbus A319"
    },
    {
     "kind": "qpxexpress#aircraftData",
     "code": "320",
     "name": "Airbus A320"
    }
   ],
   "tax": [
    {
     "kind": "qpxexpress#taxData",
     "id": "ZP",
     "name": "US Flight Segment Tax"
    },
    {
     "kind": "qpxexpress#taxData",
     "id": "XF",
     "name": "US Passenger Facility Charge"
    },
    {
     "kind": "qpxexpress#taxData",
     "id": "US_001",
     "name": "US Transportation Tax"
    },
    {
     "kind": "qpxexpress#taxData",
     "id": "AY_001",
     "name": "US September 11th Security Fee"
    }
   ],
   "carrier": [
    {
     "kind": "qpxexpress#carrierData",
     "code": "VX",
     "name": "Virgin America Inc."
    }
   ]
  },
  "tripOption": [
   {
    "kind": "qpxexpress#tripOption",
    "saleTotal": "USD76.10",
    "id": "gJ1XzttZivQTLq4onXXhuB002",
    "slice": [
     {
      "kind": "qpxexpress#sliceInfo",
      "duration": 80,
      "segment": [
       {
        "kind": "qpxexpress#segmentInfo",
        "duration": 80,
        "flight": {
         "carrier": "VX",
         "number": "898"
        },
        "id": "Gh2x6-RPI-2pEzT-",
        "cabin": "COACH",
        "bookingCode": "S",
        "bookingCodeCount": 7,
        "marriedSegmentGroup": "0",
        "leg": [
         {
          "kind": "qpxexpress#legInfo",
          "id": "LwGynWiC-abXQsov",
          "aircraft": "319",
          "arrivalTime": "2015-06-01T09:55-07:00",
          "departureTime": "2015-06-01T08:35-07:00",
          "origin": "SFO",
          "destination": "LAX",
          "originTerminal": "2",
          "destinationTerminal": "3",
          "duration": 80,
          "mileage": 337,
          "secure": true
         }
        ]
       }
      ]
     }
    ],
    "pricing": [
     {
      "kind": "qpxexpress#pricingInfo",
      "fare": [
       {
        "kind": "qpxexpress#fareInfo",
        "id": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "carrier": "VX",
        "origin": "SFO",
        "destination": "LAX",
        "basisCode": "S21NR"
       }
      ],
      "segmentPricing": [
       {
        "kind": "qpxexpress#segmentPricing",
        "fareId": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "segmentId": "Gh2x6-RPI-2pEzT-",
        "freeBaggageOption": [
         {
          "kind": "qpxexpress#freeBaggageAllowance",
          "pieces": 0
         }
        ]
       }
      ],
      "baseFareTotal": "USD57.67",
      "saleFareTotal": "USD57.67",
      "saleTaxTotal": "USD18.43",
      "saleTotal": "USD76.10",
      "passengers": {
       "kind": "qpxexpress#passengerCounts",
       "adultCount": 1
      },
      "tax": [
       {
        "kind": "qpxexpress#taxInfo",
        "id": "US_001",
        "chargeType": "GOVERNMENT",
        "code": "US",
        "country": "US",
        "salePrice": "USD4.33"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "AY_001",
        "chargeType": "GOVERNMENT",
        "code": "AY",
        "country": "US",
        "salePrice": "USD5.60"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "XF",
        "chargeType": "GOVERNMENT",
        "code": "XF",
        "country": "US",
        "salePrice": "USD4.50"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "ZP",
        "chargeType": "GOVERNMENT",
        "code": "ZP",
        "country": "US",
        "salePrice": "USD4.00"
       }
      ],
      "fareCalculation": "SFO VX LAX 57.67S21NR USD 57.67 END ZP SFO XT 4.33US 4.00ZP 5.60AY 4.50XF SFO4.50",
      "latestTicketingTime": "2015-03-12T23:59-04:00",
      "ptc": "ADT"
     }
    ]
   },
   {
    "kind": "qpxexpress#tripOption",
    "saleTotal": "USD76.10",
    "id": "gJ1XzttZivQTLq4onXXhuB005",
    "slice": [
     {
      "kind": "qpxexpress#sliceInfo",
      "duration": 80,
      "segment": [
       {
        "kind": "qpxexpress#segmentInfo",
        "duration": 80,
        "flight": {
         "carrier": "VX",
         "number": "932"
        },
        "id": "GoCBk91NLC7BcEwR",
        "cabin": "COACH",
        "bookingCode": "S",
        "bookingCodeCount": 7,
        "marriedSegmentGroup": "0",
        "leg": [
         {
          "kind": "qpxexpress#legInfo",
          "id": "LTtGHtLkc8UoL1B4",
          "aircraft": "320",
          "arrivalTime": "2015-06-01T17:50-07:00",
          "departureTime": "2015-06-01T16:30-07:00",
          "origin": "SFO",
          "destination": "LAX",
          "originTerminal": "2",
          "destinationTerminal": "3",
          "duration": 80,
          "mileage": 337,
          "secure": true
         }
        ]
       }
      ]
     }
    ],
    "pricing": [
     {
      "kind": "qpxexpress#pricingInfo",
      "fare": [
       {
        "kind": "qpxexpress#fareInfo",
        "id": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "carrier": "VX",
        "origin": "SFO",
        "destination": "LAX",
        "basisCode": "S21NR"
       }
      ],
      "segmentPricing": [
       {
        "kind": "qpxexpress#segmentPricing",
        "fareId": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "segmentId": "GoCBk91NLC7BcEwR",
        "freeBaggageOption": [
         {
          "kind": "qpxexpress#freeBaggageAllowance",
          "pieces": 0
         }
        ]
       }
      ],
      "baseFareTotal": "USD57.67",
      "saleFareTotal": "USD57.67",
      "saleTaxTotal": "USD18.43",
      "saleTotal": "USD76.10",
      "passengers": {
       "kind": "qpxexpress#passengerCounts",
       "adultCount": 1
      },
      "tax": [
       {
        "kind": "qpxexpress#taxInfo",
        "id": "US_001",
        "chargeType": "GOVERNMENT",
        "code": "US",
        "country": "US",
        "salePrice": "USD4.33"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "AY_001",
        "chargeType": "GOVERNMENT",
        "code": "AY",
        "country": "US",
        "salePrice": "USD5.60"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "XF",
        "chargeType": "GOVERNMENT",
        "code": "XF",
        "country": "US",
        "salePrice": "USD4.50"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "ZP",
        "chargeType": "GOVERNMENT",
        "code": "ZP",
        "country": "US",
        "salePrice": "USD4.00"
       }
      ],
      "fareCalculation": "SFO VX LAX 57.67S21NR USD 57.67 END ZP SFO XT 4.33US 4.00ZP 5.60AY 4.50XF SFO4.50",
      "latestTicketingTime": "2015-03-12T23:59-04:00",
      "ptc": "ADT"
     }
    ]
   },
   {
    "kind": "qpxexpress#tripOption",
    "saleTotal": "USD76.10",
    "id": "gJ1XzttZivQTLq4onXXhuB004",
    "slice": [
     {
      "kind": "qpxexpress#sliceInfo",
      "duration": 80,
      "segment": [
       {
        "kind": "qpxexpress#segmentInfo",
        "duration": 80,
        "flight": {
         "carrier": "VX",
         "number": "928"
        },
        "id": "GlaUEjnoPP-wC-Tk",
        "cabin": "COACH",
        "bookingCode": "S",
        "bookingCodeCount": 7,
        "marriedSegmentGroup": "0",
        "leg": [
         {
          "kind": "qpxexpress#legInfo",
          "id": "LfMxHD3My9DCJnP5",
          "aircraft": "320",
          "arrivalTime": "2015-06-01T14:45-07:00",
          "departureTime": "2015-06-01T13:25-07:00",
          "origin": "SFO",
          "destination": "LAX",
          "originTerminal": "2",
          "destinationTerminal": "3",
          "duration": 80,
          "onTimePerformance": 94,
          "mileage": 337,
          "secure": true
         }
        ]
       }
      ]
     }
    ],
    "pricing": [
     {
      "kind": "qpxexpress#pricingInfo",
      "fare": [
       {
        "kind": "qpxexpress#fareInfo",
        "id": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "carrier": "VX",
        "origin": "SFO",
        "destination": "LAX",
        "basisCode": "S21NR"
       }
      ],
      "segmentPricing": [
       {
        "kind": "qpxexpress#segmentPricing",
        "fareId": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "segmentId": "GlaUEjnoPP-wC-Tk",
        "freeBaggageOption": [
         {
          "kind": "qpxexpress#freeBaggageAllowance",
          "pieces": 0
         }
        ]
       }
      ],
      "baseFareTotal": "USD57.67",
      "saleFareTotal": "USD57.67",
      "saleTaxTotal": "USD18.43",
      "saleTotal": "USD76.10",
      "passengers": {
       "kind": "qpxexpress#passengerCounts",
       "adultCount": 1
      },
      "tax": [
       {
        "kind": "qpxexpress#taxInfo",
        "id": "US_001",
        "chargeType": "GOVERNMENT",
        "code": "US",
        "country": "US",
        "salePrice": "USD4.33"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "AY_001",
        "chargeType": "GOVERNMENT",
        "code": "AY",
        "country": "US",
        "salePrice": "USD5.60"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "XF",
        "chargeType": "GOVERNMENT",
        "code": "XF",
        "country": "US",
        "salePrice": "USD4.50"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "ZP",
        "chargeType": "GOVERNMENT",
        "code": "ZP",
        "country": "US",
        "salePrice": "USD4.00"
       }
      ],
      "fareCalculation": "SFO VX LAX 57.67S21NR USD 57.67 END ZP SFO XT 4.33US 4.00ZP 5.60AY 4.50XF SFO4.50",
      "latestTicketingTime": "2015-03-12T23:59-04:00",
      "ptc": "ADT"
     }
    ]
   },
   {
    "kind": "qpxexpress#tripOption",
    "saleTotal": "USD76.10",
    "id": "gJ1XzttZivQTLq4onXXhuB001",
    "slice": [
     {
      "kind": "qpxexpress#sliceInfo",
      "duration": 75,
      "segment": [
       {
        "kind": "qpxexpress#segmentInfo",
        "duration": 75,
        "flight": {
         "carrier": "VX",
         "number": "922"
        },
        "id": "GnOSuRi4g-UsfeL6",
        "cabin": "COACH",
        "bookingCode": "S",
        "bookingCodeCount": 7,
        "marriedSegmentGroup": "0",
        "leg": [
         {
          "kind": "qpxexpress#legInfo",
          "id": "LXlHxDzEt-ns00Pl",
          "aircraft": "320",
          "arrivalTime": "2015-06-01T08:05-07:00",
          "departureTime": "2015-06-01T06:50-07:00",
          "origin": "SFO",
          "destination": "LAX",
          "originTerminal": "2",
          "destinationTerminal": "3",
          "duration": 75,
          "onTimePerformance": 96,
          "mileage": 337,
          "secure": true
         }
        ]
       }
      ]
     }
    ],
    "pricing": [
     {
      "kind": "qpxexpress#pricingInfo",
      "fare": [
       {
        "kind": "qpxexpress#fareInfo",
        "id": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "carrier": "VX",
        "origin": "SFO",
        "destination": "LAX",
        "basisCode": "S21NR"
       }
      ],
      "segmentPricing": [
       {
        "kind": "qpxexpress#segmentPricing",
        "fareId": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "segmentId": "GnOSuRi4g-UsfeL6",
        "freeBaggageOption": [
         {
          "kind": "qpxexpress#freeBaggageAllowance",
          "pieces": 0
         }
        ]
       }
      ],
      "baseFareTotal": "USD57.67",
      "saleFareTotal": "USD57.67",
      "saleTaxTotal": "USD18.43",
      "saleTotal": "USD76.10",
      "passengers": {
       "kind": "qpxexpress#passengerCounts",
       "adultCount": 1
      },
      "tax": [
       {
        "kind": "qpxexpress#taxInfo",
        "id": "US_001",
        "chargeType": "GOVERNMENT",
        "code": "US",
        "country": "US",
        "salePrice": "USD4.33"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "AY_001",
        "chargeType": "GOVERNMENT",
        "code": "AY",
        "country": "US",
        "salePrice": "USD5.60"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "XF",
        "chargeType": "GOVERNMENT",
        "code": "XF",
        "country": "US",
        "salePrice": "USD4.50"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "ZP",
        "chargeType": "GOVERNMENT",
        "code": "ZP",
        "country": "US",
        "salePrice": "USD4.00"
       }
      ],
      "fareCalculation": "SFO VX LAX 57.67S21NR USD 57.67 END ZP SFO XT 4.33US 4.00ZP 5.60AY 4.50XF SFO4.50",
      "latestTicketingTime": "2015-03-12T23:59-04:00",
      "ptc": "ADT"
     }
    ]
   },
   {
    "kind": "qpxexpress#tripOption",
    "saleTotal": "USD76.10",
    "id": "gJ1XzttZivQTLq4onXXhuB003",
    "slice": [
     {
      "kind": "qpxexpress#sliceInfo",
      "duration": 80,
      "segment": [
       {
        "kind": "qpxexpress#segmentInfo",
        "duration": 80,
        "flight": {
         "carrier": "VX",
         "number": "924"
        },
        "id": "GgoEGYhqM5UeSrQL",
        "cabin": "COACH",
        "bookingCode": "S",
        "bookingCodeCount": 7,
        "marriedSegmentGroup": "0",
        "leg": [
         {
          "kind": "qpxexpress#legInfo",
          "id": "LA8jnQJ5KelX0R5q",
          "aircraft": "320",
          "arrivalTime": "2015-06-01T12:55-07:00",
          "departureTime": "2015-06-01T11:35-07:00",
          "origin": "SFO",
          "destination": "LAX",
          "originTerminal": "2",
          "destinationTerminal": "3",
          "duration": 80,
          "onTimePerformance": 94,
          "mileage": 337,
          "secure": true
         }
        ]
       }
      ]
     }
    ],
    "pricing": [
     {
      "kind": "qpxexpress#pricingInfo",
      "fare": [
       {
        "kind": "qpxexpress#fareInfo",
        "id": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "carrier": "VX",
        "origin": "SFO",
        "destination": "LAX",
        "basisCode": "S21NR"
       }
      ],
      "segmentPricing": [
       {
        "kind": "qpxexpress#segmentPricing",
        "fareId": "As7+HYACdUY6r3h0RmeuoJmeL/Fjg8V2glf7yLe8M/Wg",
        "segmentId": "GgoEGYhqM5UeSrQL",
        "freeBaggageOption": [
         {
          "kind": "qpxexpress#freeBaggageAllowance",
          "pieces": 0
         }
        ]
       }
      ],
      "baseFareTotal": "USD57.67",
      "saleFareTotal": "USD57.67",
      "saleTaxTotal": "USD18.43",
      "saleTotal": "USD76.10",
      "passengers": {
       "kind": "qpxexpress#passengerCounts",
       "adultCount": 1
      },
      "tax": [
       {
        "kind": "qpxexpress#taxInfo",
        "id": "US_001",
        "chargeType": "GOVERNMENT",
        "code": "US",
        "country": "US",
        "salePrice": "USD4.33"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "AY_001",
        "chargeType": "GOVERNMENT",
        "code": "AY",
        "country": "US",
        "salePrice": "USD5.60"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "XF",
        "chargeType": "GOVERNMENT",
        "code": "XF",
        "country": "US",
        "salePrice": "USD4.50"
       },
       {
        "kind": "qpxexpress#taxInfo",
        "id": "ZP",
        "chargeType": "GOVERNMENT",
        "code": "ZP",
        "country": "US",
        "salePrice": "USD4.00"
       }
      ],
      "fareCalculation": "SFO VX LAX 57.67S21NR USD 57.67 END ZP SFO XT 4.33US 4.00ZP 5.60AY 4.50XF SFO4.50",
      "latestTicketingTime": "2015-03-12T23:59-04:00",
      "ptc": "ADT"
     }
    ]
   }
  ]
 }
}
